"""empty message

Revision ID: 52974ec7934a
Revises: 8f03ccb733cc
Create Date: 2019-01-28 13:36:02.328120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52974ec7934a'
down_revision = '8f03ccb733cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_sites_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'sites_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sites_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_sites_id_fkey', 'users', 'sites', ['sites_id'], ['id'])
    # ### end Alembic commands ###
