"""empty message

Revision ID: 8f03ccb733cc
Revises: ef832eb18371
Create Date: 2019-01-28 13:00:41.081785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f03ccb733cc'
down_revision = 'ef832eb18371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_column('sites', 'user_id')
    # ### end Alembic commands ###
