"""empty message

Revision ID: a983f8736e15
Revises: b34a8dece7ed
Create Date: 2019-01-27 18:20:52.915444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a983f8736e15'
down_revision = 'b34a8dece7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sites_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'sites', ['sites_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sites_id')
    # ### end Alembic commands ###
