"""empty message

Revision ID: ef832eb18371
Revises: a983f8736e15
Create Date: 2019-01-27 18:24:12.872264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef832eb18371'
down_revision = 'a983f8736e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sites_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sites', ['sites_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sites_id')
    # ### end Alembic commands ###
