"""empty message

Revision ID: 10364daef15e
Revises: 4b9f09696ec9
Create Date: 2018-03-18 16:14:53.736332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10364daef15e'
down_revision = '4b9f09696ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('is_working', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'is_working')
    # ### end Alembic commands ###
